hue.rb: process with pid 82784 started.
hue.rb: process with pid 82879 started.
hue.rb: process with pid 83391 started.
hue.rb: process with pid 83741 started.
/Users/chae/01_DBC/DBC/huedaemon/lamp_controller.rb:8:in `initialize': undefined local variable or method `__dir__' for #<LampController:0x007fd0d881f410> (NameError)
	from hue.rb:11:in `new'
	from hue.rb:11:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 83881 started.
/Users/chae/01_DBC/DBC/huedaemon/lamp_controller.rb:8:in `initialize': undefined local variable or method `__dir__' for #<LampController:0x007fc13b01f4b0> (NameError)
	from hue.rb:11:in `new'
	from hue.rb:11:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 83967 started.
/Users/chae/01_DBC/DBC/huedaemon/lamp_controller.rb:8:in `initialize': undefined local variable or method `_dir_' for #<LampController:0x007fb9d081f5b0> (NameError)
	from hue.rb:11:in `new'
	from hue.rb:11:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 84207 started.
/Users/chae/01_DBC/DBC/huedaemon
/Users/chae/01_DBC/DBC/huedaemon/lamp_controller.rb:9:in `initialize': undefined local variable or method `__dir__' for #<LampController:0x007f852301f810> (NameError)
	from hue.rb:11:in `new'
	from hue.rb:11:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 84303 started.
/Users/chae/01_DBC/DBC/huedaemon
/Users/chae/01_DBC/DBC/huedaemon/lamp_controller.rb:10:in `initialize': undefined local variable or method `__dir__' for #<LampController:0x007fd2fb81f7b0> (NameError)
	from hue.rb:11:in `new'
	from hue.rb:11:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 85038 started.
/Users/chae/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych.rb:297:in `initialize': No such file or directory - /pi.yaml (Errno::ENOENT)
	from /Users/chae/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych.rb:297:in `open'
	from /Users/chae/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych.rb:297:in `load_file'
	from /Users/chae/01_DBC/DBC/huedaemon/lamp_controller.rb:10:in `initialize'
	from hue.rb:11:in `new'
	from hue.rb:11:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 85225 started.
/Users/chae/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych.rb:297:in `initialize': No such file or directory - /pi.yaml (Errno::ENOENT)
	from /Users/chae/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych.rb:297:in `open'
	from /Users/chae/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/psych.rb:297:in `load_file'
	from /Users/chae/01_DBC/DBC/huedaemon/lamp_controller.rb:11:in `initialize'
	from hue.rb:11:in `new'
	from hue.rb:11:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 85271 started.
hue.rb: process with pid 85692 started.
hue.rb: process with pid 85942 started.
hue.rb: process with pid 85988 started.
hue.rb: process with pid 86083 started.
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:8:in `initialize': undefined local variable or method `__dir__' for #<LampController:0x007fb16281f4a0> (NameError)
	from hue.rb:11:in `new'
	from hue.rb:11:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 86127 started.
hue.rb: process with pid 89039 started.
hue.rb: process with pid 14429 started.
/Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/json-1.8.0/lib/json/common.rb:155:in `parse': 795: unexpected token at '<!DOCTYPE html> (MultiJson::LoadError)
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Action Controller: Exception caught</title>
  <style>
    body {
      background-color: #FAFAFA;
      color: #333;
      margin: 0px;
    }

    body, p, ol, ul, td {
      font-family: helvetica, verdana, arial, sans-serif;
      font-size:   13px;
      line-height: 18px;
    }

    pre {
      font-size: 11px;
      white-space: pre-wrap;
    }

    pre.box {
      border: 1px solid #EEE;
      padding: 10px;
      margin: 0px;
      width: 958px;
    }

    header {
      color: #F0F0F0;
      background: #C52F24;
      padding: 0.5em 1.5em;
    }

    h1 {
      margin: 0.2em 0;
      line-height: 1.1em;
      font-size: 2em;
    }

    h2 {
      color: #C52F24;
      line-height: 25px;
    }

    .details {
      border: 1px solid #D0D0D0;
      border-radius: 4px;
      margin: 1em 0px;
      display: block;
      width: 978px;
    }

    .summary {
      padding: 8px 15px;
      border-bottom: 1px solid #D0D0D0;
      display: block;
    }

    .details pre {
      margin: 5px;
      border: none;
    }

    #container {
      box-sizing: border-box;
      width: 100%;
      padding: 0 1.5em;
    }

    .source * {
      margin: 0px;
      padding: 0px;
    }

    .source {
      border: 1px solid #D9D9D9;
      background: #ECECEC;
      width: 978px;
    }

    .source pre {
      padding: 10px 0px;
      border: none;
    }

    .source .data {
      font-size: 80%;
      overflow: auto;
      background-color: #FFF;
    }

    .info {
      padding: 0.5em;
    }

    .source .data .line_numbers {
      background-color: #ECECEC;
      color: #AAA;
      padding: 1em .5em;
      border-right: 1px solid #DDD;
      text-align: right;
    }

    .line {
      padding-left: 10px;
    }

    .line:hover {
      background-color: #F6F6F6;
    }

    .line.active {
      background-color: #FFCCCC;
    }

    a { color: #980905; }
    a:visited { color: #666; }
    a:hover { color: #C52F24; }

      #route_table {
    margin: 0 auto 0;
    border-collapse: collapse;
  }

  #route_table td {
    padding: 0 30px;
  }

  #route_table tr.bottom th {
    padding-bottom: 10px;
    line-height: 15px;
  }

  #route_table .matched_paths {
    background-color: LightGoldenRodYellow;
  }

  #route_table .matched_paths {
    border-bottom: solid 3px SlateGrey;
  }

  #path_search {
    width: 80%;
    font-size: inherit;
  }

  </style>

  <script>
    var toggle = function(id) {
      var s = document.getElementById(id).style;
      s.display = s.display == 'none' ? 'block' : 'none';
      return false;
    }
    var show = function(id) {
      document.getElementById(id).style.display = 'block';
    }
    var hide = function(id) {
      document.getElementById(id).style.display = 'none';
    }
    var toggleTrace = function() {
      return toggle('blame_trace');
    }
    var toggleSessionDump = function() {
      return toggle('session_dump');
    }
    var toggleEnvDump = function() {
      return toggle('env_dump');
    }
  </script>
</head>
<body>

<header>
  <h1>Routing Error</h1>
</header>
<div id="container">
  <h2>No route matches [GET] &quot;/api&quot;</h2>


<p><code>Rails.root: /Users/chae/01_DBC/DBC/huemorme</code></p>

<div id="traces">
    <a href="#" onclick="hide(&#39;Framework-Trace&#39;);hide(&#39;Full-Trace&#39;);show(&#39;Application-Trace&#39;);; return false;">Application Trace</a> |
    <a href="#" onclick="hide(&#39;Application-Trace&#39;);hide(&#39;Full-Trace&#39;);show(&#39;Framework-Trace&#39;);; return false;">Framework Trace</a> |
    <a href="#" onclick="hide(&#39;Application-Trace&#39;);hide(&#39;Framework-Trace&#39;);show(&#39;Full-Trace&#39;);; return false;">Full Trace</a>

    <div id="Application-Trace" style="display: block;">
      <pre><code></code></pre>
    </div>
    <div id="Framework-Trace" style="display: none;">
      <pre><code>actionpack (4.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call&#39;
actionpack (4.0.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call&#39;
railties (4.0.0) lib/rails/rack/logger.rb:38:in `call_app&#39;
railties (4.0.0) lib/rails/rack/logger.rb:23:in `call&#39;
actionpack (4.0.0) lib/action_dispatch/middleware/request_id.rb:21:in `call&#39;
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call&#39;
rack (1.5.2) lib/rack/runtime.rb:17:in `call&#39;
activesupport (4.0.0) lib/active_support/cache/strategy/local_cache.rb:83:in `call&#39;
rack (1.5.2) lib/rack/lock.rb:17:in `call&#39;
actionpack (4.0.0) lib/action_dispatch/middleware/static.rb:64:in `call&#39;
railties (4.0.0) lib/rails/engine.rb:511:in `call&#39;
railties (4.0.0) lib/rails/application.rb:97:in `call&#39;
rack (1.5.2) lib/rack/lock.rb:17:in `call&#39;
rack (1.5.2) lib/rack/content_length.rb:14:in `call&#39;
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service&#39;
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service&#39;
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run&#39;
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread&#39;</code></pre>
    </div>
    <div id="Full-Trace" style="display: none;">
      <pre><code>actionpack (4.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call&#39;
actionpack (4.0.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call&#39;
railties (4.0.0) lib/rails/rack/logger.rb:38:in `call_app&#39;
railties (4.0.0) lib/rails/rack/logger.rb:23:in `call&#39;
actionpack (4.0.0) lib/action_dispatch/middleware/request_id.rb:21:in `call&#39;
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call&#39;
rack (1.5.2) lib/rack/runtime.rb:17:in `call&#39;
activesupport (4.0.0) lib/active_support/cache/strategy/local_cache.rb:83:in `call&#39;
rack (1.5.2) lib/rack/lock.rb:17:in `call&#39;
actionpack (4.0.0) lib/action_dispatch/middleware/static.rb:64:in `call&#39;
railties (4.0.0) lib/rails/engine.rb:511:in `call&#39;
railties (4.0.0) lib/rails/application.rb:97:in `call&#39;
rack (1.5.2) lib/rack/lock.rb:17:in `call&#39;
rack (1.5.2) lib/rack/content_length.rb:14:in `call&#39;
rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service&#39;
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service&#39;
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run&#39;
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread&#39;</code></pre>
    </div>
</div>


    <h2>
      Routes
    </h2>

    <p>
      Routes match in priority from top to bottom
    </p>


<table id='route_table' class='route_table'>
  <thead>
    <tr>
      <th>Helper</th>
      <th>HTTP Verb</th>
      <th>Path</th>
      <th>Controller#Action</th>
    </tr>
    <tr class='bottom'>
      <th>
        <a data-route-helper="_path" href="#" title="Returns a relative path (without the http or domain)">Path</a> /
        <a data-route-helper="_url" href="#" title="Returns an absolute url (with the http and domain)">Url</a>
      </th>
      <th>
      </th>
      <th>
        <input id="path_search" name="path[]" placeholder="Path Match" type="search" />
      </th>
      <th>
      </th>
    </tr>
  </thead>
  <tbody class='matched_paths' id='matched_paths'>
  </tbody>
  <tbody>
    <tr class='route_row' data-helper='path'>
  <td data-route-name='user_bridges'>
      user_bridges<span class='helper'>_path</span>
  </td>
  <td data-route-verb='POST'>
    POST
  </td>
  <td data-route-path='/users/:user_id/bridges(.:format)' data-regexp='^\/users\/([^\/.?]+)\/bridges(?:\.([^\/.?]+))?$'>
    /users/:user_id/bridges(.:format)
  </td>
  <td data-route-reqs='bridges#create'>
    bridges#create
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='new_user_bridge'>
      new_user_bridge<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/users/:user_id/bridges/new(.:format)' data-regexp='^\/users\/([^\/.?]+)\/bridges\/new(?:\.([^\/.?]+))?$'>
    /users/:user_id/bridges/new(.:format)
  </td>
  <td data-route-reqs='bridges#new'>
    bridges#new
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='edit_user_bridge'>
      edit_user_bridge<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/users/:user_id/bridges/:id/edit(.:format)' data-regexp='^\/users\/([^\/.?]+)\/bridges\/([^\/.?]+)\/edit(?:\.([^\/.?]+))?$'>
    /users/:user_id/bridges/:id/edit(.:format)
  </td>
  <td data-route-reqs='bridges#edit'>
    bridges#edit
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='user_bridge'>
      user_bridge<span class='helper'>_path</span>
  </td>
  <td data-route-verb='PATCH'>
    PATCH
  </td>
  <td data-route-path='/users/:user_id/bridges/:id(.:format)' data-regexp='^\/users\/([^\/.?]+)\/bridges\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /users/:user_id/bridges/:id(.:format)
  </td>
  <td data-route-reqs='bridges#update'>
    bridges#update
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name=''>
  </td>
  <td data-route-verb='PUT'>
    PUT
  </td>
  <td data-route-path='/users/:user_id/bridges/:id(.:format)' data-regexp='^\/users\/([^\/.?]+)\/bridges\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /users/:user_id/bridges/:id(.:format)
  </td>
  <td data-route-reqs='bridges#update'>
    bridges#update
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='users'>
      users<span class='helper'>_path</span>
  </td>
  <td data-route-verb='POST'>
    POST
  </td>
  <td data-route-path='/users(.:format)' data-regexp='^\/users(?:\.([^\/.?]+))?$'>
    /users(.:format)
  </td>
  <td data-route-reqs='users#create'>
    users#create
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='new_user'>
      new_user<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/users/new(.:format)' data-regexp='^\/users\/new(?:\.([^\/.?]+))?$'>
    /users/new(.:format)
  </td>
  <td data-route-reqs='users#new'>
    users#new
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='user'>
      user<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/users/:id(.:format)' data-regexp='^\/users\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /users/:id(.:format)
  </td>
  <td data-route-reqs='users#show'>
    users#show
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='settings_bridge_lamp'>
      settings_bridge_lamp<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/bridges/:bridge_id/lamps/:id/settings(.:format)' data-regexp='^\/bridges\/([^\/.?]+)\/lamps\/([^\/.?]+)\/settings(?:\.([^\/.?]+))?$'>
    /bridges/:bridge_id/lamps/:id/settings(.:format)
  </td>
  <td data-route-reqs='lamps#settings'>
    lamps#settings
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='bridge_lamps'>
      bridge_lamps<span class='helper'>_path</span>
  </td>
  <td data-route-verb='POST'>
    POST
  </td>
  <td data-route-path='/bridges/:bridge_id/lamps(.:format)' data-regexp='^\/bridges\/([^\/.?]+)\/lamps(?:\.([^\/.?]+))?$'>
    /bridges/:bridge_id/lamps(.:format)
  </td>
  <td data-route-reqs='lamps#create'>
    lamps#create
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='bridge'>
      bridge<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/bridges/:id(.:format)' data-regexp='^\/bridges\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /bridges/:id(.:format)
  </td>
  <td data-route-reqs='bridges#show'>
    bridges#show
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='sessions'>
      sessions<span class='helper'>_path</span>
  </td>
  <td data-route-verb='POST'>
    POST
  </td>
  <td data-route-path='/sessions(.:format)' data-regexp='^\/sessions(?:\.([^\/.?]+))?$'>
    /sessions(.:format)
  </td>
  <td data-route-reqs='sessions#create'>
    sessions#create
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='session'>
      session<span class='helper'>_path</span>
  </td>
  <td data-route-verb='DELETE'>
    DELETE
  </td>
  <td data-route-path='/sessions/:id(.:format)' data-regexp='^\/sessions\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /sessions/:id(.:format)
  </td>
  <td data-route-reqs='sessions#destroy'>
    sessions#destroy
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='root'>
      root<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/' data-regexp='^\/$'>
    /
  </td>
  <td data-route-reqs='users#show'>
    users#show
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='signout'>
      signout<span class='helper'>_path</span>
  </td>
  <td data-route-verb='DELETE'>
    DELETE
  </td>
  <td data-route-path='/signout(.:format)' data-regexp='^\/signout(?:\.([^\/.?]+))?$'>
    /signout(.:format)
  </td>
  <td data-route-reqs='sessions#destroy'>
    sessions#destroy
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name=''>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/api/:secret_token(.:format)' data-regexp='^\/api\/([^\/.?]+)(?:\.([^\/.?]+))?$'>
    /api/:secret_token(.:format)
  </td>
  <td data-route-reqs='apis#show'>
    apis#show
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='setup'>
      setup<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/setup(.:format)' data-regexp='^\/setup(?:\.([^\/.?]+))?$'>
    /setup(.:format)
  </td>
  <td data-route-reqs='users#setup'>
    users#setup
  </td>
</tr>
<tr class='route_row' data-helper='path'>
  <td data-route-name='download'>
      download<span class='helper'>_path</span>
  </td>
  <td data-route-verb='GET'>
    GET
  </td>
  <td data-route-path='/download(.:format)' data-regexp='^\/download(?:\.([^\/.?]+))?$'>
    /download(.:format)
  </td>
  <td data-route-reqs='users#download'>
    users#download
  </td>
</tr>

  </tbody>
</table>

<script type='text/javascript'>
  function each(elems, func) {
    if (!elems instanceof Array) { elems = [elems]; }
    for (var i = 0, len = elems.length; i < len; i++) {
      func(elems[i]);
    }
  }

  function setValOn(elems, val) {
    each(elems, function(elem) {
      elem.innerHTML = val;
    });
  }

  function onClick(elems, func) {
    each(elems, function(elem) {
      elem.onclick = func;
    });
  }

  // Enables functionality to toggle between `_path` and `_url` helper suffixes
  function setupRouteToggleHelperLinks() {
    var toggleLinks = document.querySelectorAll('#route_table [data-route-helper]');
    onClick(toggleLinks, function(){
      var helperTxt   = this.getAttribute("data-route-helper"),
          helperElems = document.querySelectorAll('[data-route-name] span.helper');
      setValOn(helperElems, helperTxt);
    });
  }

  // takes an array of elements with a data-regexp attribute and
  // passes their their parent <tr> into the callback function
  // if the regexp matchs a given path
  function eachElemsForPath(elems, path, func) {
    each(elems, function(e){
      var reg = e.getAttribute("data-regexp");
      if (path.match(RegExp(reg))) {
        func(e.parentNode.cloneNode(true));
      }
    })
  }

  // Ensure path always starts with a slash "/" and remove params or fragments
  function sanitizePath(path) {
    var path = path.charAt(0) == '/' ? path : "/" + path;
    return path.replace(/\#.*|\?.*/, '');
  }

  // Enables path search functionality
  function setupMatchPaths() {
    var regexpElems     = document.querySelectorAll('#route_table [data-regexp]'),
        pathElem        = document.querySelector('#path_search'),
        selectedSection = document.querySelector('#matched_paths'),
        noMatchText     = '<tr><th colspan="4">None</th></tr>';


    // Remove matches if no path is present
    pathElem.onblur = function(e) {
      if (pathElem.value === "") selectedSection.innerHTML = "";
    }

    // On key press perform a search for matching paths
    pathElem.onkeyup = function(e){
      var path        = sanitizePath(pathElem.value),
          defaultText = '<tr><th colspan="4">Paths Matching (' + path + '):</th></tr>';

      // Clear out results section
      selectedSection.innerHTML= defaultText;

      // Display matches if they exist
      eachElemsForPath(regexpElems, path, function(e){
        selectedSection.appendChild(e);
      });

      // If no match present, tell the user
      if (selectedSection.innerHTML === defaultText) {
        selectedSection.innerHTML = selectedSection.innerHTML + noMatchText;
      }
    }
  }

  setupMatchPaths();
  setupRouteToggleHelperLinks();
</script>

</div>


</body>
</html>
'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/json-1.8.0/lib/json/common.rb:155:in `parse'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/multi_json-1.8.0/lib/multi_json/adapters/json_common.rb:16:in `load'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/multi_json-1.8.0/lib/multi_json/adapter.rb:20:in `load'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/multi_json-1.8.0/lib/multi_json.rb:120:in `load'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:14:in `get_server'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:6:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 14510 started.
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:477:in `get_response'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:454:in `get'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:14:in `get_server'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:6:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 14570 started.
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:477:in `get_response'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:454:in `get'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:15:in `get_server'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:7:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 14600 started.
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:477:in `get_response'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:454:in `get'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:15:in `get_server'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:7:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 14695 started.
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:477:in `get_response'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:454:in `get'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:15:in `get_server'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:7:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 14724 started.
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:477:in `get_response'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:454:in `get'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:15:in `get_server'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:7:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 14901 started.
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:477:in `get_response'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:454:in `get'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:15:in `get_server'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:8:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 14933 started.
/Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:582:in `start'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:477:in `get_response'
	from /Users/chae/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:454:in `get'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:15:in `get_server'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:8:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 15134 started.
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp.rb:16:in `send_command': nil is not a symbol (TypeError)
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:21:in `block in lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `each'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:10:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 15168 started.
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp.rb:16:in `send_command': nil is not a symbol (TypeError)
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:21:in `block in lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `each'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:10:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 15367 started.
/Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:21:in `block (2 levels) in lamp_updater': undefined local variable or method `commands' for #<LampController:0x007ff0ec108f08> (NameError)
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:20:in `each'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:20:in `block in lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `each'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:10:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 15780 started.
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:8:in `initialize': undefined local variable or method `__dir__' for #<LampController:0x007fe92281f368> (NameError)
	from hue.rb:11:in `new'
	from hue.rb:11:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 16419 started.
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:8:in `initialize': undefined local variable or method `__dir__' for #<LampController:0x007f88b881f310> (NameError)
	from hue.rb:11:in `new'
	from hue.rb:11:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 16448 started.
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:8:in `initialize': undefined local variable or method `__dir__' for #<LampController:0x007fa56a81f2b0> (NameError)
	from hue.rb:11:in `new'
	from hue.rb:11:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 16608 started.
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp.rb:8:in `initialize': wrong number of arguments (2 for 3..4) (ArgumentError)
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:20:in `new'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:20:in `block in lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `each'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:10:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 16642 started.
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp.rb:8:in `initialize': wrong number of arguments (2 for 3..4) (ArgumentError)
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:20:in `new'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:20:in `block in lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `each'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:10:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 16701 started.
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp.rb:8:in `initialize': wrong number of arguments (2 for 3..4) (ArgumentError)
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:20:in `new'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:20:in `block in lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `each'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:10:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 16737 started.
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp.rb:8:in `initialize': wrong number of arguments (2 for 3..4) (ArgumentError)
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:20:in `new'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:20:in `block in lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `each'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:10:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 17204 started.
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp.rb:8:in `initialize': wrong number of arguments (2 for 3..4) (ArgumentError)
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `new'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:19:in `block in lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:18:in `each'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:18:in `lamp_updater'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/pi_controller.rb:9:in `update'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:13:in `block in run'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `loop'
	from /Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:12:in `run'
	from hue.rb:12:in `block in <main>'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/chae/.rvm/gems/ruby-2.0.0-p247@huemorme/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from hue.rb:10:in `<main>'
hue.rb: process with pid 17363 started.
hue.rb: process with pid 17449 started.
hue.rb: process with pid 17618 started.
hue.rb: process with pid 18615 started.
