# Logfile created on 2013-10-12 20:18:42 -0400 by logger.rb/31641
I, [2013-10-12T20:18:42.874523 #6966]  INFO -- : *** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
E, [2013-10-12T20:18:42.874715 #6966] ERROR -- : exception reentered (fatal)

I, [2013-10-12T20:18:42.874802 #6966]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2013-10-12T20:18:42.874897 #6966] ERROR -- : undefined local variable or method `__dir__' for #<LampController:0x007fce7901f1e0> (NameError)
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:8:in `initialize'
hue.rb:11:in `new'
hue.rb:11:in `block in <main>'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
hue.rb:10:in `<main>'
E, [2013-10-12T20:18:42.875513 #6966] ERROR -- : stream closed (IOError)

E, [2013-10-12T20:18:42.875610 #6966] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2013-10-12T20:18:42.875695 #6966] ERROR -- : stack level too deep (SystemStackError)

E, [2013-10-12T20:18:42.875894 #6966] ERROR -- : exception reentered (fatal)

I, [2013-10-12T20:19:03.805780 #6990]  INFO -- : *** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
E, [2013-10-12T20:19:03.806064 #6990] ERROR -- : exception reentered (fatal)

I, [2013-10-12T20:19:03.806169 #6990]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2013-10-12T20:19:03.806286 #6990] ERROR -- : undefined local variable or method `__dir__' for #<LampController:0x007f82dc01f1d8> (NameError)
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:8:in `initialize'
hue.rb:11:in `new'
hue.rb:11:in `block in <main>'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
hue.rb:10:in `<main>'
E, [2013-10-12T20:19:03.807004 #6990] ERROR -- : stream closed (IOError)

E, [2013-10-12T20:19:03.807107 #6990] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2013-10-12T20:19:03.807197 #6990] ERROR -- : stack level too deep (SystemStackError)

E, [2013-10-12T20:19:03.807403 #6990] ERROR -- : exception reentered (fatal)

I, [2013-10-12T20:19:25.070623 #7011]  INFO -- : *** below you find the most recent exception thrown, this will be likely (but not certainly) the exception that made the application exit abnormally ***
E, [2013-10-12T20:19:25.070853 #7011] ERROR -- : exception reentered (fatal)

I, [2013-10-12T20:19:25.070937 #7011]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2013-10-12T20:19:25.071031 #7011] ERROR -- : undefined local variable or method `__dir__' for #<LampController:0x007f841201f1b0> (NameError)
/Users/chae/01_DBC/DBC/huedaemon/lib/lamp_controller.rb:8:in `initialize'
hue.rb:11:in `new'
hue.rb:11:in `block in <main>'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/Users/chae/.rvm/gems/ruby-1.9.3-p448@rails3.2.11/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
hue.rb:10:in `<main>'
E, [2013-10-12T20:19:25.071760 #7011] ERROR -- : stream closed (IOError)

E, [2013-10-12T20:19:25.071860 #7011] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2013-10-12T20:19:25.071942 #7011] ERROR -- : stack level too deep (SystemStackError)

E, [2013-10-12T20:19:25.072128 #7011] ERROR -- : exception reentered (fatal)

